name: bagel
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=78.1=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - accelerate==1.12.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.49.0
      - brotli==1.2.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.2
      - decord==0.6.0
      - dill==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - fastapi==0.128.0
      - ffmpy==1.0.0
      - filelock==3.20.1
      - flash-attn==2.7.4.post1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==5.38.2
      - gradio-client==1.11.0
      - groovy==0.1.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.29.1
      - idna==3.11
      - jinja2==3.1.6
      - json5==0.12.1
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.7.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.7.0.72
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - platformdirs==4.5.1
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.2.1
      - pyarrow==22.0.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.11.3
      - requests==2.32.3
      - rich==14.2.0
      - ruff==0.14.10
      - safehttpx==0.1.7
      - safetensors==0.4.5
      - scipy==1.10.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.48.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - starlette==0.50.0
      - sympy==1.13.1
      - tokenizers==0.21.4
      - tomlkit==0.13.3
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.2.0
      - typer==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - wandb==0.23.1
      - websockets==15.0.1
      - xlsxwriter==3.2.9
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /data/group/zhaolab/project/miniconda/envs/bagel
